# Welcome to Serverless!
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: fleet-customer-api
app: fleet-customer-api
tenant: louisdeslandesfleet

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs10.x
  tracing:
    apiGateway: true
    lambda: true
  region: us-east-2

functions:
  customerapi:
    handler: handler.handler
    events:
      - http: ANY /{proxy+}
